### ISSUE TITLE
Unexpected Behavior When Using Flexbox

### ISSUE THREAD

**Issue by bradonomics** [sparanoid/lightense-images#61]
I'm getting unexpected behavior when using flexbox to align images.

![lightense-flexbox](https://user-images.githubusercontent.com/5723185/124033254-5b610d00-d9bf-11eb-856b-4627a3f97c12.gif)

As you can see, the images are moving around before the overlay is applied. But, even worse, the last image doesn't center itself as it should.

The markup:

```html
<div class="gallery">
  <img src="images/18.jpg">
  <img src="images/19.jpg">
  <img src="images/20.jpg">
</div>
```

The styles:

```css
.gallery {
  display: flex;
  flex-wrap: wrap;
}

.gallery img {
  flex-grow: 1;
  margin: 0 .25rem .5rem;
  width: 30%;
}
```

Is there something I can change in the config to have it perform as expected?

**Comment by sparanoid** [comment]
Please wrap images inside a `div`:

```html
<div class="gallery">
  <div><img src="https://d349cztnlupsuf.cloudfront.net/girls_dead_monster_logo.png" /></div>
  <div><img src="https://d349cztnlupsuf.cloudfront.net/girls_dead_monster_logo.png" /></div>
  <div><img src="https://d349cztnlupsuf.cloudfront.net/girls_dead_monster_logo.png" /></div>
</div>
```

```css
.gallery {
  display: flex;
  flex-wrap: wrap;
}

.gallery > div {
  flex-grow: 1;
  margin: 0 .25rem .5rem;
  width: 30%;
}
```

I've also included an example `demo.html`.
